steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: [
      'build',
      '--no-cache',
      '-t',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '.',
      '-f',
      'Dockerfile'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [
      'push',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: gcloud
    args: [
      'run',
      'services',
      'update',
      '$_SERVICE_NAME',
      '--platform=managed',
      '--image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID',
      '--region=$_DEPLOY_REGION',
      '--quiet'
    ]
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: europe-west4
  _AR_HOSTNAME: eu.gcr.io
  _TRIGGER_ID: ef153364-2803-48d0-81fa-25c59e54bb7c
  _PLATFORM: managed
  _SERVICE_NAME: pipeline